version: '2.3'
services:
  nginx:
    image: openresty/openresty
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./nginx/config:/etc/nginx/conf.d"
      - "./nginx/log:/var/log/nginx"
      - "./nginx/cert:/cert"